#############################################################################
# Makefile for building: InverterController
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Oct 29 15:58:47 2013
# Project:  InverterController.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile InverterController.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		invertercontroller.cpp \
		keyboard.cpp \
		mainface.cpp \
		mcontroller.cpp \
		minputcontext.cpp \
		runinfoface.cpp \
		submenu.cpp \
		toolbar.cpp \
		functiontable.cpp \
		DataBase.cpp \
		clock.cpp \
		chart.cpp \
		serial/serialport.cpp \
		serial/mserialoperate.cpp \
		historyinfoface.cpp \
		paramsetface.cpp \
		powerface.cpp \
		historydata.cpp \
		operafile.cpp \
		runparasetface.cpp \
		setparadialog.cpp \
		parainfo.cpp \
		paratablewidget.cpp \
		faultdialog.cpp \
		historyfault.cpp \
		clocksetface.cpp \
		systemparaface.cpp \
		userfile.cpp moc_invertercontroller.cpp \
		moc_keyboard.cpp \
		moc_mainface.cpp \
		moc_mcontroller.cpp \
		moc_minputcontext.cpp \
		moc_powerface.cpp \
		moc_runinfoface.cpp \
		moc_submenu.cpp \
		moc_toolbar.cpp \
		moc_functiontable.cpp \
		moc_clock.cpp \
		moc_chart.cpp \
		moc_mserialoperate.cpp \
		moc_historyinfoface.cpp \
		moc_paramsetface.cpp \
		moc_runparasetface.cpp \
		moc_setparadialog.cpp \
		moc_paratablewidget.cpp \
		moc_faultdialog.cpp \
		moc_clocksetface.cpp \
		moc_systemparaface.cpp \
		qrc_InverterController.cpp
OBJECTS       = main.o \
		invertercontroller.o \
		keyboard.o \
		mainface.o \
		mcontroller.o \
		minputcontext.o \
		runinfoface.o \
		submenu.o \
		toolbar.o \
		functiontable.o \
		DataBase.o \
		clock.o \
		chart.o \
		serialport.o \
		mserialoperate.o \
		historyinfoface.o \
		paramsetface.o \
		powerface.o \
		historydata.o \
		operafile.o \
		runparasetface.o \
		setparadialog.o \
		parainfo.o \
		paratablewidget.o \
		faultdialog.o \
		historyfault.o \
		clocksetface.o \
		systemparaface.o \
		userfile.o \
		moc_invertercontroller.o \
		moc_keyboard.o \
		moc_mainface.o \
		moc_mcontroller.o \
		moc_minputcontext.o \
		moc_powerface.o \
		moc_runinfoface.o \
		moc_submenu.o \
		moc_toolbar.o \
		moc_functiontable.o \
		moc_clock.o \
		moc_chart.o \
		moc_mserialoperate.o \
		moc_historyinfoface.o \
		moc_paramsetface.o \
		moc_runparasetface.o \
		moc_setparadialog.o \
		moc_paratablewidget.o \
		moc_faultdialog.o \
		moc_clocksetface.o \
		moc_systemparaface.o \
		qrc_InverterController.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		InverterController.pro
QMAKE_TARGET  = InverterController
DESTDIR       = 
TARGET        = InverterController

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_invertercontroller.h ui_keyboard.h ui_mainface.h ui_submenu.h ui_toolbar.h ui_clock.h ui_chart.h ui_setparadialog.h ui_clocksetface.h ui_historydata.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: InverterController.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile InverterController.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile InverterController.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/InverterController1.0.0 || $(MKDIR) .tmp/InverterController1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/InverterController1.0.0/ && $(COPY_FILE) --parents invertercontroller.h keyboard.h mainface.h mcontroller.h minputcontext.h powerface.h runinfoface.h submenu.h toolbar.h functiontable.h DataBase.h clock.h chart.h serial/serialport.h serial/mserialoperate.h common.h historyinfoface.h paramsetface.h historydata.h operafile.h runparasetface.h setparadialog.h parainfo.h paratablewidget.h faultdialog.h historyfault.h clocksetface.h systemparaface.h userfile.h .tmp/InverterController1.0.0/ && $(COPY_FILE) --parents InverterController.qrc .tmp/InverterController1.0.0/ && $(COPY_FILE) --parents main.cpp invertercontroller.cpp keyboard.cpp mainface.cpp mcontroller.cpp minputcontext.cpp runinfoface.cpp submenu.cpp toolbar.cpp functiontable.cpp DataBase.cpp clock.cpp chart.cpp serial/serialport.cpp serial/mserialoperate.cpp historyinfoface.cpp paramsetface.cpp powerface.cpp historydata.cpp operafile.cpp runparasetface.cpp setparadialog.cpp parainfo.cpp paratablewidget.cpp faultdialog.cpp historyfault.cpp clocksetface.cpp systemparaface.cpp userfile.cpp .tmp/InverterController1.0.0/ && $(COPY_FILE) --parents invertercontroller.ui keyboard.ui mainface.ui submenu.ui toolbar.ui clock.ui chart.ui setparadialog.ui clocksetface.ui historydata.ui .tmp/InverterController1.0.0/ && (cd `dirname .tmp/InverterController1.0.0` && $(TAR) InverterController1.0.0.tar InverterController1.0.0 && $(COMPRESS) InverterController1.0.0.tar) && $(MOVE) `dirname .tmp/InverterController1.0.0`/InverterController1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/InverterController1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_invertercontroller.cpp moc_keyboard.cpp moc_mainface.cpp moc_mcontroller.cpp moc_minputcontext.cpp moc_powerface.cpp moc_runinfoface.cpp moc_submenu.cpp moc_toolbar.cpp moc_functiontable.cpp moc_clock.cpp moc_chart.cpp moc_mserialoperate.cpp moc_historyinfoface.cpp moc_paramsetface.cpp moc_runparasetface.cpp moc_setparadialog.cpp moc_paratablewidget.cpp moc_faultdialog.cpp moc_clocksetface.cpp moc_systemparaface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_invertercontroller.cpp moc_keyboard.cpp moc_mainface.cpp moc_mcontroller.cpp moc_minputcontext.cpp moc_powerface.cpp moc_runinfoface.cpp moc_submenu.cpp moc_toolbar.cpp moc_functiontable.cpp moc_clock.cpp moc_chart.cpp moc_mserialoperate.cpp moc_historyinfoface.cpp moc_paramsetface.cpp moc_runparasetface.cpp moc_setparadialog.cpp moc_paratablewidget.cpp moc_faultdialog.cpp moc_clocksetface.cpp moc_systemparaface.cpp
moc_invertercontroller.cpp: ui_invertercontroller.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		submenu.h \
		ui_submenu.h \
		invertercontroller.h \
		invertercontroller.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) invertercontroller.h -o moc_invertercontroller.cpp

moc_keyboard.cpp: ui_keyboard.h \
		keyboard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyboard.h -o moc_keyboard.cpp

moc_mainface.cpp: ui_mainface.h \
		chart.h \
		ui_chart.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		mainface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainface.h -o moc_mainface.cpp

moc_mcontroller.cpp: common.h \
		parainfo.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		mcontroller.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mcontroller.h -o moc_mcontroller.cpp

moc_minputcontext.cpp: minputcontext.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) minputcontext.h -o moc_minputcontext.cpp

moc_powerface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		powerface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) powerface.h -o moc_powerface.cpp

moc_runinfoface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		chart.h \
		ui_chart.h \
		paratablewidget.h \
		runinfoface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) runinfoface.h -o moc_runinfoface.cpp

moc_submenu.cpp: ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		submenu.h \
		submenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) submenu.h -o moc_submenu.cpp

moc_toolbar.cpp: ui_toolbar.h \
		clock.h \
		ui_clock.h \
		toolbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) toolbar.h -o moc_toolbar.cpp

moc_functiontable.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		functiontable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) functiontable.h -o moc_functiontable.cpp

moc_clock.cpp: ui_clock.h \
		clock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clock.h -o moc_clock.cpp

moc_chart.cpp: ui_chart.h \
		chart.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) chart.h -o moc_chart.cpp

moc_mserialoperate.cpp: common.h \
		parainfo.h \
		serial/serialport.h \
		serial/mserialoperate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) serial/mserialoperate.h -o moc_mserialoperate.cpp

moc_historyinfoface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		historyinfoface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) historyinfoface.h -o moc_historyinfoface.cpp

moc_paramsetface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		paramsetface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) paramsetface.h -o moc_paramsetface.cpp

moc_runparasetface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		setparadialog.h \
		paratablewidget.h \
		runparasetface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) runparasetface.h -o moc_runparasetface.cpp

moc_setparadialog.cpp: common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		setparadialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) setparadialog.h -o moc_setparadialog.cpp

moc_paratablewidget.cpp: common.h \
		parainfo.h \
		paratablewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) paratablewidget.h -o moc_paratablewidget.cpp

moc_faultdialog.cpp: common.h \
		parainfo.h \
		faultdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) faultdialog.h -o moc_faultdialog.cpp

moc_clocksetface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		ui_clocksetface.h \
		clocksetface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clocksetface.h -o moc_clocksetface.cpp

moc_systemparaface.cpp: submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		systemparaface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) systemparaface.h -o moc_systemparaface.cpp

compiler_rcc_make_all: qrc_InverterController.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_InverterController.cpp
qrc_InverterController.cpp: InverterController.qrc \
		images/fault.png \
		images/gongnengbiao.png \
		images/comm.png \
		images/shangyiye.png \
		images/redled.png \
		images/private.png \
		images/yunxingxinxi.png \
		images/event.png \
		images/fanhui.png \
		images/greenled.png \
		images/lishixinxi.png \
		images/canshushezi.png \
		images/zhuyemian.png \
		images/mainbeijing.png \
		images/xiayiye.png \
		images/kaiguanji.png \
		images/run.png \
		images/mainpic.png \
		images/data.png \
		Resources/fault.xml \
		Resources/parameter.xml
	/usr/bin/rcc -name InverterController InverterController.qrc -o qrc_InverterController.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_invertercontroller.h ui_keyboard.h ui_mainface.h ui_submenu.h ui_toolbar.h ui_clock.h ui_chart.h ui_setparadialog.h ui_clocksetface.h ui_historydata.h
compiler_uic_clean:
	-$(DEL_FILE) ui_invertercontroller.h ui_keyboard.h ui_mainface.h ui_submenu.h ui_toolbar.h ui_clock.h ui_chart.h ui_setparadialog.h ui_clocksetface.h ui_historydata.h
ui_invertercontroller.h: invertercontroller.ui \
		clock.h \
		ui_clock.h
	/usr/bin/uic-qt4 invertercontroller.ui -o ui_invertercontroller.h

ui_keyboard.h: keyboard.ui
	/usr/bin/uic-qt4 keyboard.ui -o ui_keyboard.h

ui_mainface.h: mainface.ui \
		chart.h \
		ui_chart.h
	/usr/bin/uic-qt4 mainface.ui -o ui_mainface.h

ui_submenu.h: submenu.ui \
		clock.h \
		ui_clock.h
	/usr/bin/uic-qt4 submenu.ui -o ui_submenu.h

ui_toolbar.h: toolbar.ui \
		clock.h \
		ui_clock.h
	/usr/bin/uic-qt4 toolbar.ui -o ui_toolbar.h

ui_clock.h: clock.ui
	/usr/bin/uic-qt4 clock.ui -o ui_clock.h

ui_chart.h: chart.ui
	/usr/bin/uic-qt4 chart.ui -o ui_chart.h

ui_setparadialog.h: setparadialog.ui
	/usr/bin/uic-qt4 setparadialog.ui -o ui_setparadialog.h

ui_clocksetface.h: clocksetface.ui
	/usr/bin/uic-qt4 clocksetface.ui -o ui_clocksetface.h

ui_historydata.h: historydata.ui \
		chart.h \
		ui_chart.h
	/usr/bin/uic-qt4 historydata.ui -o ui_historydata.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp minputcontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

invertercontroller.o: invertercontroller.cpp invertercontroller.h \
		ui_invertercontroller.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		submenu.h \
		ui_submenu.h \
		mainface.h \
		ui_mainface.h \
		chart.h \
		ui_chart.h \
		functiontable.h \
		powerface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o invertercontroller.o invertercontroller.cpp

keyboard.o: keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o keyboard.cpp

mainface.o: mainface.cpp mainface.h \
		ui_mainface.h \
		chart.h \
		ui_chart.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		faultdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainface.o mainface.cpp

mcontroller.o: mcontroller.cpp mcontroller.h \
		common.h \
		parainfo.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		operafile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mcontroller.o mcontroller.cpp

minputcontext.o: minputcontext.cpp keyboard.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minputcontext.o minputcontext.cpp

runinfoface.o: runinfoface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runinfoface.o runinfoface.cpp

submenu.o: submenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o submenu.o submenu.cpp

toolbar.o: toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbar.o toolbar.cpp

functiontable.o: functiontable.cpp invertercontroller.h \
		ui_invertercontroller.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		submenu.h \
		ui_submenu.h \
		paramsetface.h \
		runinfoface.h \
		chart.h \
		ui_chart.h \
		paratablewidget.h \
		historyinfoface.h \
		powerface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functiontable.o functiontable.cpp

DataBase.o: DataBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataBase.o DataBase.cpp

clock.o: clock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clock.o clock.cpp

chart.o: chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chart.o chart.cpp

serialport.o: serial/serialport.cpp serial/serialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialport.o serial/serialport.cpp

mserialoperate.o: serial/mserialoperate.cpp serial/mserialoperate.h \
		common.h \
		parainfo.h \
		serial/serialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mserialoperate.o serial/mserialoperate.cpp

historyinfoface.o: historyinfoface.cpp historyinfoface.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		historydata.h \
		ui_historydata.h \
		chart.h \
		ui_chart.h \
		historyfault.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historyinfoface.o historyinfoface.cpp

paramsetface.o: paramsetface.cpp paramsetface.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		operafile.h \
		runparasetface.h \
		setparadialog.h \
		paratablewidget.h \
		systemparaface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paramsetface.o paramsetface.cpp

powerface.o: powerface.cpp powerface.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerface.o powerface.cpp

historydata.o: historydata.cpp historydata.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		ui_historydata.h \
		chart.h \
		ui_chart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historydata.o historydata.cpp

operafile.o: operafile.cpp operafile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operafile.o operafile.cpp

runparasetface.o: runparasetface.cpp runparasetface.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		setparadialog.h \
		paratablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runparasetface.o runparasetface.cpp

setparadialog.o: setparadialog.cpp setparadialog.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		ui_setparadialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setparadialog.o setparadialog.cpp

parainfo.o: parainfo.cpp parainfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parainfo.o parainfo.cpp

paratablewidget.o: paratablewidget.cpp paratablewidget.h \
		common.h \
		parainfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paratablewidget.o paratablewidget.cpp

faultdialog.o: faultdialog.cpp faultdialog.h \
		common.h \
		parainfo.h \
		operafile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faultdialog.o faultdialog.cpp

historyfault.o: historyfault.cpp historyfault.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historyfault.o historyfault.cpp

clocksetface.o: clocksetface.cpp clocksetface.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		ui_clocksetface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clocksetface.o clocksetface.cpp

systemparaface.o: systemparaface.cpp systemparaface.h \
		submenu.h \
		ui_submenu.h \
		clock.h \
		ui_clock.h \
		common.h \
		parainfo.h \
		mcontroller.h \
		DataBase.h \
		serial/mserialoperate.h \
		serial/serialport.h \
		invertercontroller.h \
		ui_invertercontroller.h \
		clocksetface.h \
		ui_clocksetface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemparaface.o systemparaface.cpp

userfile.o: userfile.cpp userfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userfile.o userfile.cpp

moc_invertercontroller.o: moc_invertercontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_invertercontroller.o moc_invertercontroller.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

moc_mainface.o: moc_mainface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainface.o moc_mainface.cpp

moc_mcontroller.o: moc_mcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mcontroller.o moc_mcontroller.cpp

moc_minputcontext.o: moc_minputcontext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minputcontext.o moc_minputcontext.cpp

moc_powerface.o: moc_powerface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_powerface.o moc_powerface.cpp

moc_runinfoface.o: moc_runinfoface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runinfoface.o moc_runinfoface.cpp

moc_submenu.o: moc_submenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_submenu.o moc_submenu.cpp

moc_toolbar.o: moc_toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolbar.o moc_toolbar.cpp

moc_functiontable.o: moc_functiontable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_functiontable.o moc_functiontable.cpp

moc_clock.o: moc_clock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clock.o moc_clock.cpp

moc_chart.o: moc_chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chart.o moc_chart.cpp

moc_mserialoperate.o: moc_mserialoperate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mserialoperate.o moc_mserialoperate.cpp

moc_historyinfoface.o: moc_historyinfoface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_historyinfoface.o moc_historyinfoface.cpp

moc_paramsetface.o: moc_paramsetface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paramsetface.o moc_paramsetface.cpp

moc_runparasetface.o: moc_runparasetface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runparasetface.o moc_runparasetface.cpp

moc_setparadialog.o: moc_setparadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setparadialog.o moc_setparadialog.cpp

moc_paratablewidget.o: moc_paratablewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paratablewidget.o moc_paratablewidget.cpp

moc_faultdialog.o: moc_faultdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faultdialog.o moc_faultdialog.cpp

moc_clocksetface.o: moc_clocksetface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clocksetface.o moc_clocksetface.cpp

moc_systemparaface.o: moc_systemparaface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemparaface.o moc_systemparaface.cpp

qrc_InverterController.o: qrc_InverterController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_InverterController.o qrc_InverterController.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

